const banksection6 = {
  1: ["image/img/sec6/burger/b1.png",
    "image/img/sec6/burger/b2.png",
    "image/img/sec6/burger/b3.png",
    "image/img/sec6/burger/b4.png",
    "image/img/sec6/burger/b5.png",
    "image/img/sec6/burger/b6.png",
    "image/img/sec6/burger/b7.png",
    "image/img/sec6/burger/b8.png",
    "image/img/sec6/burger/b9.png",
    "image/img/sec6/burger/b10.png",
    "image/img/sec6/burger/b11.png",
    "image/img/sec6/burger/b12.png"],
  2: ["image/img/sec6/pizza/p1.png",
    "image/img/sec6/pizza/p2.png",
    "image/img/sec6/pizza/p3.png",
    "image/img/sec6/pizza/p4.png",
    "image/img/sec6/pizza/p5.png",
    "image/img/sec6/pizza/p6.png",
    "image/img/sec6/pizza/p7.png",
    "image/img/sec6/pizza/p8.png",
    "image/img/sec6/pizza/p9.png",
    "image/img/sec6/pizza/p10.png",
    "image/img/sec6/pizza/p11.png",
    "image/img/sec6/pizza/p12.png",
    "image/img/sec6/pizza/p13.png",
    "image/img/sec6/pizza/p14.png"],
  3: ["image/img/sec6/drink/d1.png",
    "image/img/sec6/drink/d2.png",
    "image/img/sec6/drink/d3.png",
    "image/img/sec6/drink/d4.png",
    "image/img/sec6/drink/d5.png",
    "image/img/sec6/drink/d6.png",
    "image/img/sec6/drink/d7.png",
    "image/img/sec6/drink/d8.png",
    "image/img/sec6/drink/d9.png",
    "image/img/sec6/drink/d10.png",
    "image/img/sec6/drink/d11.png",
    "image/img/sec6/drink/d12.png",
    "image/img/sec6/drink/d13.png",
    "image/img/sec6/drink/d14.png"],
  4: ["image/img/sec6/pasta/p1.png",
    "image/img/sec6/pasta/p2.png",
    "image/img/sec6/pasta/p3.png",
    "image/img/sec6/pasta/p4.png",
    "image/img/sec6/pasta/p2.png",],
  5: ["image/img/sec6/soup/so1.png",
    "image/img/sec6/soup/so2.png",
    "image/img/sec6/soup/so3.png",
    "image/img/sec6/soup/so4.png",
    "image/img/sec6/soup/so1.png"],
  6: ["image/img/sec6/sushi/s1.png",
    "image/img/sec6/sushi/s2.png",
    "image/img/sec6/sushi/s3.png",
    "image/img/sec6/sushi/s4.png",
    "image/img/sec6/sushi/s5.png",
    "image/img/sec6/sushi/s6.png"]
};

const bankSection6_detail = {
  1: ["چیزبرگر ویژه بوقلمون", "دابل برگر", "آنگوس برگر", "برگر بوفالو", "برگر کیوی", "برگر ایتالیایی", "برگر پورک", "برگر 50/50", "چیلی برگر ویژه", "برگر مک دونالد", "برگر ذغالی", "وگان برگر"],
  2: ["پیتزا ویژه", "پیتزا برلوسکونی", "پیتزا هاوایی", "پیتزا هاگیز", "پیتزا مینی", "پیتزا مارگاریتا", "پیتزا گوشت", "پیتزا مخصوص", "پیتزا ناپل", "پیتزا تارت مرغ", "پیتزا تارت گوشت", "پیتزا دیترویت", " پیتزا وگان", "پیتزا دریایی وِیژه"],
  3: ["شیک نوتلا مخصوص", "آب پرتغال", "شیرموز", "آب انبه", "پالپ هلو", "توت فرنگی", "کیوی", "دراگون", "شیک کارامل", "آب سیب", "بلوبری", "لیموناد", "لیموناد ویژه", "آب هویج"],
  4: ["پاستا وگان", "ایتالیانو", "دریایی", "پاستا گوشت", "ایتالیانو"],
  5: ["سوپ ویژه دریایی", "سوپ کدوتنبل", "سوپ چینی", "سوپ گوجه", "سوپ دریایی ویژه"],
  6: ["سوشی سرآشپز", "خاویار", "گوشت", "موز", "تریپل سوشی", "ماهی و میگو"],
}
const bankSection6_superdetail = {
  1: ["80درصد گوشت بوقلمون , پنیر گودا , کاهو , گوجه , پیاز",
    "800 گرم گوشت گوساله , پنیر چدار ورقه ای , کاهو , گوجه , پیاز",
    "400 گرم گوشت گاو آنگوس , پنیر گودا , 100 گرم جگر گاو آنگوس , کاهو , گوجه",
    "500 گرم گوشت بوفالو آمریکایی , پنیر ورقه ای چدار , کاهو برزیلی , گوجه , پیاز",
    " 400 گرم گوشت گاو , پنیر چدار , چغندر , پیاز , سس مخصوص ",
    "400 گرم گوشت گاو بدون چربی, پنیر ورقه ای چدار , سبزی روکولا , سس مخصوص , جعفری تازه و آویشن , نان سیبا",
    "سینه مرغ , قارچ , پنیر گودا , کاهو , خیارشور , گوجه و پیاز",
    "50درصد بیکن, 50درصد گوشت گوساله , کاهو , خیارشور , گوجه , پیاز",
    "300گرم گوشت گاو 80 درصد, رست بیف , پنیر ورقه ای چدار , سس ویژه",
    "350گرم گوشت گاو 100درصد, پنیر گودا , کاهو , گوجه , سس مخصوص مک دونالد",
    "گوشت چرخ کرده , قارچ , خیارشور , کاهو , گوجه",
    "کاهو, پودر زنجبیل , گوجه , خیار , قارچ"],
  2: ["گوشت خوک , پاپریکا , ذرت , قارچ",
    "گوشت دودی گوزن , پنیر فنلاندی , زیتون تلخ , سس مخصوص",
    "پنیر , آناناس , کوکتل میوه ای , اژدها , سوسیس",
    "جگر گوسفند, دانه های معطر اسکاتلندی , پنیرپیتزا مخصوص",
    "پنیر, کالباس , قارچ , فلفل دلمه ای",
    "پنیر, ریحان , گوجه فرنگی",
    "بیکن , زیتون , گوشت چرخ کرده , پنیر ناپل",
    "کالباس, پنیر ویژه , قارچ , سینه مرغ , بیکن , بیف",
    "پنیر لانگوس, خامه ترش , سیر , کره , گوجه فرنگی , زیتون , گوشت خوک",
    "سینه گریل, پنیر , زیتون , ریحان , ذرت",
    "بیکن گوساله , پنیر ایتالیایی , فلفل , قارچ",
    "سوسیس پپرونی, سس گوجه , پنیر رنده فوگا , ریحان",
    "قارچ, زیتون , سینه مرغ , زیتون ,فلفل دلمه ای , ذرت , ریحان",
    "اختاپوس, صدف , میگو , پنیر ایتالیایی",
  ],
  3: ["-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-", "-"],
  4: ["-", "-", "-", "-", "-"],
  5: ["-", "-", "-", "-", "-"],
  6: ["-", "-", "-", "-", "-", "-"],
}
const bankordersec6 = {
  1: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  2: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  3: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  4: [0, 0, 0, 0, 0],
  5: [0, 0, 0, 0, 0],
  6: [0, 0, 0, 0, 0, 0],
  all: 0,
}
const bankpricesec6 = {
  1: [120, 145, 99, 150, 60, 80, 85, 95, 89, 70, 85, 40],
  2: [65, 115, 110, 85, 50, 90, 95, 100, 105, 80, 120, 75, 65, 165],
  3: [55, 30, 35, 50, 45, 60, 35, 120, 40, 25, 80, 40, 50, 25],
  4: [35, 30, 55, 40, 30],
  5: [70, 44, 35, 25, 70],
  6: [30, 25, 40, 42, 90, 120],
}
export { banksection6, bankSection6_detail, bankSection6_superdetail, bankordersec6, bankpricesec6 };